import type { ThemeConfig } from 'antd';

export const theme: ThemeConfig = {
  token: {
    colorPrimary: '#FF7D00',
    colorSuccess: '#16A34A',
    colorInfo: '#2563EB',
    colorWarning: '#CA8A04',
    colorError: '#DC2626',
    colorBgLayout: '#F7F8FA',
    colorBorderSecondary: '#F0F0F0',
    borderRadiusLG: 11,
    borderRadius: 8,
    borderRadiusSM: 6,
    fontFamily: 'var(--co-font-sans)',
  },
  components: {
    Table: {
      headerBg: 'transparent',
      headerColor: '#9CA3AF',
      headerSplitColor: 'transparent',
      rowHoverBg: '#F9FAFB',
      borderColor: '#F3F4F6',
      cellPaddingBlock: 12,
      cellPaddingInline: 12,
      cellFontSize: 13,
    },
    Button: {
      borderRadius: 8,
      borderRadiusSM: 6,
      controlHeight: 36,
      controlHeightSM: 30,
      contentFontSize: 13,
      contentFontSizeSM: 12,
      fontWeight: 500,
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
      defaultBorderColor: '#E5E7EB',
      defaultColor: '#4B5563',
      defaultHoverBg: '#F9FAFB',
      defaultHoverColor: '#111827',
      defaultHoverBorderColor: '#E5E7EB',
      textTextColor: '#6B7280',
      textTextHoverColor: '#111827',
      textHoverBg: '#F3F4F6',
    },
    Tag: {
      borderRadiusSM: 6,
      defaultBg: '#F9FAFB',
      defaultColor: '#6B7280',
      fontSizeSM: 12,
      lineHeightSM: 1.2,
    },
    Tabs: {
      inkBarColor: '#FF7D00',
      itemColor: '#6B7280',
      itemHoverColor: '#111827',
      itemActiveColor: '#FF7D00',
      itemSelectedColor: '#FF7D00',
      titleFontSize: 13,
    },
    Card: {
      bodyPadding: 20,
      borderRadiusLG: 11,
      colorBorderSecondary: '#F0F0F0',
    },
  },
};
